#!/bin/bash

file="$1";

if [ ${file: -5} == ".html" ]
then
cat << EOF > "$file"
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />

    <title></title>
    <style></style>
  </head>

  <body>
    <script></script>
  </body>
</html>
EOF
fi
